.TH PROXY 1 "2024-04-21" "macOS X.Y" "General Commands Manual"

.SH NAME
proxy \- run commands through proxy

.SH SYNOPSIS
.B proxy
command

.SH DESCRIPTION
The \fBproxy\fR function temporarily override the system's default proxy settings for the duration of a single command.

.SH EXAMPLES
.PP
proxy ping 8.8.8.8

.SH AUTHOR
Feilian Xie <feilian1000@gmail.com>
